### ISSUE TITLE
update for new pycharm build.

### ISSUE THREAD

**Issue by SobieskiCodes** [LukWebsForge/HasteIt#11]
Incompatible with version 193.5233.109
Hasteit loaded in fine.

> 10:27 AM	Plugin Error: Plugin "DiscordBeam" is incompatible (target build range is 183.4284.148 to 192.*).

EDIT: I'm dumb, saw the change log.

**Comment by lukbukkit** [comment]
Was it possible for you to just download an update for the working version or did had to uninstall it and download the plugin again?

**Comment by SobieskiCodes** [comment]
Had to uninstall then reinstall, not a big deal :)

**Comment by lukbukkit** [comment]
My intention was, that people just could upgrade from the now `--`-version to the normal version without a reinstall. I'm just a little sad, that it didn't work.
Anyways I guess, it would be good to write this to the README file of the repository.

Thank for your issue otherwise I wouldn't have noticed.
