### ISSUE TITLE
Dynamic plugin support

### ISSUE THREAD

**Issue by sashagam** [LukWebsForge/HasteIt#15]
Hi!

Did you managed to fix issue with dynamic plugin load?
Found your issue on jetbrains support forum:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008211319-Plugin-not-unload-safe-because-class-loader-cannot-be-unloaded

Thanks!

**Comment by lukbukkit** [comment]
Sadly I did not yet find a solution for the problem. Today I'm going to look into the memory dumps, maybe they contain something helpful. I'll keep you updated.

**Comment by lukbukkit** [comment]
The `HasteIt` plugin is now safe to unload, if no task is running. I removed all class properties which point to a service, instead I'm requesting the service instance when I need it. I did the same thing for `DiscordBeam`, but it's still impossible to unload the plugin without a restart. I guess this is a problem caused by the platform, not my plugin.

**Comment by sashagam** [comment]
Thanks for reply!

I think it is problem on intellij idea side. Hope they will fix it on future releases.
